/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CatalogItemInput = IDL.Record({
  'requiredDocuments' : IDL.Text,
  'stockStatus' : IDL.Text,
  'requiresPdfCalc' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Text,
  'mediaFiles' : IDL.Vec(ExternalBlob),
  'mediaTypes' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FilterOrders = IDL.Record({
  'status' : IDL.Opt(IDL.Text),
  'serviceType' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const OrderRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'instructions' : IDL.Text,
  'uploadedFiles' : IDL.Vec(ExternalBlob),
  'phone' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const CatalogItem = IDL.Record({
  'id' : IDL.Nat,
  'requiredDocuments' : IDL.Text,
  'stockStatus' : IDL.Text,
  'requiresPdfCalc' : IDL.Bool,
  'published' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Text,
  'mediaFiles' : IDL.Vec(ExternalBlob),
  'mediaTypes' : IDL.Vec(IDL.Text),
});
export const KhataEntry = IDL.Record({
  'customerName' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'totalDue' : IDL.Float64,
  'phone' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'deliveryRating' : IDL.Opt(IDL.Nat),
  'customerPhone' : IDL.Text,
  'serviceRating' : IDL.Nat,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'orderId' : IDL.Nat,
  'location' : IDL.Text,
  'deliveryComment' : IDL.Opt(IDL.Text),
  'serviceComment' : IDL.Text,
});
export const ShopOrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'itemId' : IDL.Nat,
  'itemName' : IDL.Text,
  'price' : IDL.Float64,
});
export const ShopOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'deliveryOtp' : IDL.Text,
  'cscFinalOutput' : IDL.Opt(ExternalBlob),
  'createdAt' : IDL.Int,
  'deliveryMethod' : IDL.Text,
  'cscDocuments' : IDL.Vec(ExternalBlob),
  'cscSpecialDetails' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'phone' : IDL.Text,
  'items' : IDL.Vec(ShopOrderItem),
});
export const SupportTicket = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'createdAt' : IDL.Int,
  'complaint' : IDL.Text,
  'customerMobile' : IDL.Text,
  'orderId' : IDL.Text,
});
export const TypesettingQuoteRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'language' : IDL.Text,
  'quoteNotes' : IDL.Text,
  'phone' : IDL.Text,
  'finalPdfUrl' : IDL.Text,
  'format' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'status' : IDL.Text,
  'date' : IDL.Text,
  'mobile' : IDL.Text,
});
export const BusinessInfo = IDL.Record({
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'customerName' : IDL.Opt(IDL.Text),
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const ExpenseEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'addedBy' : IDL.Text,
  'paymentMode' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const ManualIncomeEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'paymentMode' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const PosSaleItem = IDL.Record({
  'qty' : IDL.Nat,
  'itemName' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'totalPrice' : IDL.Float64,
});
export const PosSale = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'customerPhone' : IDL.Text,
  'staffMobile' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(PosSaleItem),
});
export const MaskedShopOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'createdAt' : IDL.Int,
  'deliveryMethod' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'phone' : IDL.Text,
  'items' : IDL.Vec(ShopOrderItem),
});
export const Rider = IDL.Record({
  'pin' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'mobile' : IDL.Text,
  'baseSalary' : IDL.Float64,
});
export const StaffLedgerEntry = IDL.Record({
  'id' : IDL.Nat,
  'entryType' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'mobile' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UpiSettings = IDL.Record({
  'upiId' : IDL.Text,
  'qrCodeUrl' : IDL.Text,
});
export const ServiceOrder = IDL.Record({
  'files' : IDL.Vec(ExternalBlob),
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'instructions' : IDL.Text,
  'phone' : IDL.Text,
});
export const TypesettingQuoteRequestInput = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'language' : IDL.Text,
  'phone' : IDL.Text,
  'format' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const TypesettingQuoteUpdate = IDL.Record({ 'status' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptDelivery' : IDL.Func([IDL.Nat], [], []),
  'addAttendanceRecord' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addCatalogItem' : IDL.Func([CatalogItemInput], [IDL.Nat], []),
  'addExpense' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addKhataDue' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Float64],
      [],
    ),
  'addManualIncome' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addStaffLedgerEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdminWithMasterKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'clearKhataDue' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Float64], []),
  'deductWallet' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Float64], []),
  'deductWalletForOrder' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Float64], []),
  'deleteCatalogItem' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteManualIncome' : IDL.Func([IDL.Nat], [], []),
  'deleteReview' : IDL.Func([IDL.Nat], [], []),
  'exportBulkLeadsToCsv' : IDL.Func([], [IDL.Text], ['query']),
  'filterOrders' : IDL.Func([FilterOrders], [IDL.Vec(OrderRecord)], ['query']),
  'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllCatalogItems' : IDL.Func([], [IDL.Vec(CatalogItem)], ['query']),
  'getAllKhataEntries' : IDL.Func([], [IDL.Vec(KhataEntry)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAllShopOrders' : IDL.Func([], [IDL.Vec(ShopOrder)], ['query']),
  'getAllSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getAllTypesettingQuotes' : IDL.Func(
      [],
      [IDL.Vec(TypesettingQuoteRequest)],
      ['query'],
    ),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceForMobile' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCatalogItem' : IDL.Func([IDL.Nat], [IDL.Opt(CatalogItem)], ['query']),
  'getCustomerProfile' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'customerName' : IDL.Text,
            'deliveryAddress' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getExpenses' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getKhataEntry' : IDL.Func([IDL.Text], [IDL.Opt(KhataEntry)], ['query']),
  'getManualIncomes' : IDL.Func([], [IDL.Vec(ManualIncomeEntry)], ['query']),
  'getOrderDeliveryOtp' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], ['query']),
  'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(OrderRecord)], ['query']),
  'getPosSales' : IDL.Func([], [IDL.Vec(PosSale)], ['query']),
  'getPosSalesByPhone' : IDL.Func([IDL.Text], [IDL.Vec(PosSale)], ['query']),
  'getPublishedCatalogItems' : IDL.Func([], [IDL.Vec(CatalogItem)], ['query']),
  'getPublishedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getReadyForDeliveryOrders' : IDL.Func(
      [],
      [IDL.Vec(MaskedShopOrder)],
      ['query'],
    ),
  'getRiders' : IDL.Func([], [IDL.Vec(Rider)], ['query']),
  'getStaffLedgerEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StaffLedgerEntry)],
      ['query'],
    ),
  'getSupportTickets' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SupportTicket)],
      ['query'],
    ),
  'getTeamMemberActive' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getUpiSettings' : IDL.Func([], [IDL.Opt(UpiSettings)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'importBulkLeadsFromCsv' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markOrderDelivered' : IDL.Func([IDL.Nat, IDL.Text], [ShopOrder], []),
  'placeCscShopOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ShopOrderItem),
        IDL.Float64,
        IDL.Vec(ExternalBlob),
        IDL.Text,
      ],
      [ShopOrder],
      [],
    ),
  'placeShopOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ShopOrderItem),
        IDL.Float64,
      ],
      [ShopOrder],
      [],
    ),
  'rechargeWallet' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Float64], []),
  'recordPosSale' : IDL.Func(
      [IDL.Vec(PosSaleItem), IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'removeRider' : IDL.Func([IDL.Text], [], []),
  'resetStaffPin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resolveSupportTicket' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCustomerProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'seedReviews' : IDL.Func([], [], []),
  'setBusinessInfo' : IDL.Func([BusinessInfo], [], []),
  'setUpiSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitOrderFull' : IDL.Func([ServiceOrder], [IDL.Nat], []),
  'submitReview' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'submitSupportTicket' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitTypesettingQuoteRequest' : IDL.Func(
      [TypesettingQuoteRequestInput],
      [IDL.Nat],
      [],
    ),
  'togglePublishCatalogItem' : IDL.Func([IDL.Nat], [], []),
  'toggleReviewPublished' : IDL.Func([IDL.Nat], [], []),
  'toggleTeamMemberActive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateCatalogItem' : IDL.Func([IDL.Nat, CatalogItemInput], [], []),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateLeadFinalPdf' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateLeadQuoteNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateManualIncome' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateRiderSalary' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateShopOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateTypesettingQuoteStatus' : IDL.Func(
      [IDL.Nat, TypesettingQuoteUpdate],
      [],
      [],
    ),
  'uploadCscFinalOutput' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'verifyBulkStaff' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'verifyRider' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'verifyStaff' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CatalogItemInput = IDL.Record({
    'requiredDocuments' : IDL.Text,
    'stockStatus' : IDL.Text,
    'requiresPdfCalc' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Text,
    'mediaFiles' : IDL.Vec(ExternalBlob),
    'mediaTypes' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FilterOrders = IDL.Record({
    'status' : IDL.Opt(IDL.Text),
    'serviceType' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const OrderRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'instructions' : IDL.Text,
    'uploadedFiles' : IDL.Vec(ExternalBlob),
    'phone' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const CatalogItem = IDL.Record({
    'id' : IDL.Nat,
    'requiredDocuments' : IDL.Text,
    'stockStatus' : IDL.Text,
    'requiresPdfCalc' : IDL.Bool,
    'published' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Text,
    'mediaFiles' : IDL.Vec(ExternalBlob),
    'mediaTypes' : IDL.Vec(IDL.Text),
  });
  const KhataEntry = IDL.Record({
    'customerName' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'totalDue' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'deliveryRating' : IDL.Opt(IDL.Nat),
    'customerPhone' : IDL.Text,
    'serviceRating' : IDL.Nat,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'orderId' : IDL.Nat,
    'location' : IDL.Text,
    'deliveryComment' : IDL.Opt(IDL.Text),
    'serviceComment' : IDL.Text,
  });
  const ShopOrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'itemId' : IDL.Nat,
    'itemName' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ShopOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'deliveryOtp' : IDL.Text,
    'cscFinalOutput' : IDL.Opt(ExternalBlob),
    'createdAt' : IDL.Int,
    'deliveryMethod' : IDL.Text,
    'cscDocuments' : IDL.Vec(ExternalBlob),
    'cscSpecialDetails' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'phone' : IDL.Text,
    'items' : IDL.Vec(ShopOrderItem),
  });
  const SupportTicket = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'createdAt' : IDL.Int,
    'complaint' : IDL.Text,
    'customerMobile' : IDL.Text,
    'orderId' : IDL.Text,
  });
  const TypesettingQuoteRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'language' : IDL.Text,
    'quoteNotes' : IDL.Text,
    'phone' : IDL.Text,
    'finalPdfUrl' : IDL.Text,
    'format' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Text,
    'date' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const BusinessInfo = IDL.Record({
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'customerName' : IDL.Opt(IDL.Text),
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ExpenseEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'addedBy' : IDL.Text,
    'paymentMode' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ManualIncomeEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'paymentMode' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const PosSaleItem = IDL.Record({
    'qty' : IDL.Nat,
    'itemName' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'totalPrice' : IDL.Float64,
  });
  const PosSale = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'customerPhone' : IDL.Text,
    'staffMobile' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(PosSaleItem),
  });
  const MaskedShopOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'createdAt' : IDL.Int,
    'deliveryMethod' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'phone' : IDL.Text,
    'items' : IDL.Vec(ShopOrderItem),
  });
  const Rider = IDL.Record({
    'pin' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'mobile' : IDL.Text,
    'baseSalary' : IDL.Float64,
  });
  const StaffLedgerEntry = IDL.Record({
    'id' : IDL.Nat,
    'entryType' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'mobile' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UpiSettings = IDL.Record({
    'upiId' : IDL.Text,
    'qrCodeUrl' : IDL.Text,
  });
  const ServiceOrder = IDL.Record({
    'files' : IDL.Vec(ExternalBlob),
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'instructions' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TypesettingQuoteRequestInput = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'language' : IDL.Text,
    'phone' : IDL.Text,
    'format' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const TypesettingQuoteUpdate = IDL.Record({ 'status' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptDelivery' : IDL.Func([IDL.Nat], [], []),
    'addAttendanceRecord' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addCatalogItem' : IDL.Func([CatalogItemInput], [IDL.Nat], []),
    'addExpense' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addKhataDue' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Float64],
        [],
      ),
    'addManualIncome' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addStaffLedgerEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdminWithMasterKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'clearKhataDue' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Float64], []),
    'deductWallet' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Float64], []),
    'deductWalletForOrder' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [IDL.Float64],
        [],
      ),
    'deleteCatalogItem' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteManualIncome' : IDL.Func([IDL.Nat], [], []),
    'deleteReview' : IDL.Func([IDL.Nat], [], []),
    'exportBulkLeadsToCsv' : IDL.Func([], [IDL.Text], ['query']),
    'filterOrders' : IDL.Func(
        [FilterOrders],
        [IDL.Vec(OrderRecord)],
        ['query'],
      ),
    'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllCatalogItems' : IDL.Func([], [IDL.Vec(CatalogItem)], ['query']),
    'getAllKhataEntries' : IDL.Func([], [IDL.Vec(KhataEntry)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAllShopOrders' : IDL.Func([], [IDL.Vec(ShopOrder)], ['query']),
    'getAllSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getAllTypesettingQuotes' : IDL.Func(
        [],
        [IDL.Vec(TypesettingQuoteRequest)],
        ['query'],
      ),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceForMobile' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCatalogItem' : IDL.Func([IDL.Nat], [IDL.Opt(CatalogItem)], ['query']),
    'getCustomerProfile' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'customerName' : IDL.Text,
              'deliveryAddress' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getExpenses' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getKhataEntry' : IDL.Func([IDL.Text], [IDL.Opt(KhataEntry)], ['query']),
    'getManualIncomes' : IDL.Func([], [IDL.Vec(ManualIncomeEntry)], ['query']),
    'getOrderDeliveryOtp' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Text],
        ['query'],
      ),
    'getOrdersByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OrderRecord)],
        ['query'],
      ),
    'getPosSales' : IDL.Func([], [IDL.Vec(PosSale)], ['query']),
    'getPosSalesByPhone' : IDL.Func([IDL.Text], [IDL.Vec(PosSale)], ['query']),
    'getPublishedCatalogItems' : IDL.Func(
        [],
        [IDL.Vec(CatalogItem)],
        ['query'],
      ),
    'getPublishedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getReadyForDeliveryOrders' : IDL.Func(
        [],
        [IDL.Vec(MaskedShopOrder)],
        ['query'],
      ),
    'getRiders' : IDL.Func([], [IDL.Vec(Rider)], ['query']),
    'getStaffLedgerEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StaffLedgerEntry)],
        ['query'],
      ),
    'getSupportTickets' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SupportTicket)],
        ['query'],
      ),
    'getTeamMemberActive' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getUpiSettings' : IDL.Func([], [IDL.Opt(UpiSettings)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'importBulkLeadsFromCsv' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markOrderDelivered' : IDL.Func([IDL.Nat, IDL.Text], [ShopOrder], []),
    'placeCscShopOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ShopOrderItem),
          IDL.Float64,
          IDL.Vec(ExternalBlob),
          IDL.Text,
        ],
        [ShopOrder],
        [],
      ),
    'placeShopOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ShopOrderItem),
          IDL.Float64,
        ],
        [ShopOrder],
        [],
      ),
    'rechargeWallet' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Float64], []),
    'recordPosSale' : IDL.Func(
        [IDL.Vec(PosSaleItem), IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'removeRider' : IDL.Func([IDL.Text], [], []),
    'resetStaffPin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resolveSupportTicket' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCustomerProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'seedReviews' : IDL.Func([], [], []),
    'setBusinessInfo' : IDL.Func([BusinessInfo], [], []),
    'setUpiSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitOrderFull' : IDL.Func([ServiceOrder], [IDL.Nat], []),
    'submitReview' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'submitSupportTicket' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitTypesettingQuoteRequest' : IDL.Func(
        [TypesettingQuoteRequestInput],
        [IDL.Nat],
        [],
      ),
    'togglePublishCatalogItem' : IDL.Func([IDL.Nat], [], []),
    'toggleReviewPublished' : IDL.Func([IDL.Nat], [], []),
    'toggleTeamMemberActive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateCatalogItem' : IDL.Func([IDL.Nat, CatalogItemInput], [], []),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateLeadFinalPdf' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateLeadQuoteNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateManualIncome' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateRiderSalary' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateShopOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateTypesettingQuoteStatus' : IDL.Func(
        [IDL.Nat, TypesettingQuoteUpdate],
        [],
        [],
      ),
    'uploadCscFinalOutput' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'verifyBulkStaff' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'verifyRider' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'verifyStaff' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };