/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TypesettingQuoteUpdate {
    status: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PosSale {
    id: bigint;
    paymentMethod: string;
    customerPhone: string;
    staffMobile: string;
    createdAt: bigint;
    totalAmount: number;
    items: Array<PosSaleItem>;
}
export interface ShopOrderItem {
    qty: bigint;
    itemId: bigint;
    itemName: string;
    price: number;
}
export interface CatalogItem {
    id: bigint;
    requiredDocuments: string;
    stockStatus: string;
    requiresPdfCalc: boolean;
    published: boolean;
    name: string;
    createdAt: bigint;
    description: string;
    category: string;
    price: string;
    mediaFiles: Array<ExternalBlob>;
    mediaTypes: Array<string>;
}
export interface ExpenseEntry {
    id: bigint;
    date: string;
    note: string;
    createdAt: bigint;
    addedBy: string;
    paymentMode: string;
    category: string;
    amount: number;
}
export interface Review {
    id: bigint;
    customerName: string;
    deliveryRating?: bigint;
    customerPhone: string;
    serviceRating: bigint;
    published: boolean;
    createdAt: bigint;
    orderId: bigint;
    location: string;
    deliveryComment?: string;
    serviceComment: string;
}
export interface ManualIncomeEntry {
    id: bigint;
    date: string;
    createdAt: bigint;
    description: string;
    paymentMode: string;
    category: string;
    amount: number;
}
export interface CatalogItemInput {
    requiredDocuments: string;
    stockStatus: string;
    requiresPdfCalc: boolean;
    name: string;
    description: string;
    category: string;
    price: string;
    mediaFiles: Array<ExternalBlob>;
    mediaTypes: Array<string>;
}
export interface KhataEntry {
    customerName: string;
    lastUpdated: bigint;
    totalDue: number;
    phone: string;
}
export interface MaskedShopOrder {
    id: bigint;
    customerName: string;
    status: string;
    deliveryAddress: string;
    paymentMethod: string;
    createdAt: bigint;
    deliveryMethod: string;
    totalAmount: number;
    phone: string;
    items: Array<ShopOrderItem>;
}
export interface ShopOrder {
    id: bigint;
    customerName: string;
    status: string;
    deliveryAddress: string;
    paymentMethod: string;
    deliveryOtp: string;
    cscFinalOutput?: ExternalBlob;
    createdAt: bigint;
    deliveryMethod: string;
    cscDocuments: Array<ExternalBlob>;
    cscSpecialDetails: string;
    totalAmount: number;
    phone: string;
    items: Array<ShopOrderItem>;
}
export interface SupportTicket {
    id: bigint;
    resolved: boolean;
    createdAt: bigint;
    complaint: string;
    customerMobile: string;
    orderId: string;
}
export interface OrderRecord {
    id: bigint;
    status: string;
    serviceType: string;
    name: string;
    submittedAt: bigint;
    instructions: string;
    uploadedFiles: Array<ExternalBlob>;
    phone: string;
    fileUrl: string;
}
export interface AttendanceRecord {
    status: string;
    date: string;
    mobile: string;
}
export interface StaffLedgerEntry {
    id: bigint;
    entryType: string;
    date: string;
    description: string;
    mobile: string;
    amount: number;
}
export interface Rider {
    pin: string;
    name: string;
    role: string;
    mobile: string;
    baseSalary: number;
}
export interface PosSaleItem {
    qty: bigint;
    itemName: string;
    unitPrice: number;
    totalPrice: number;
}
export interface FilterOrders {
    status?: string;
    serviceType?: string;
    name?: string;
    phone?: string;
}
export interface TypesettingQuoteRequestInput {
    subject: string;
    name: string;
    language: string;
    phone: string;
    format: string;
    fileUrl: string;
}
export interface ServiceOrder {
    files: Array<ExternalBlob>;
    serviceType: string;
    name: string;
    instructions: string;
    phone: string;
}
export interface TypesettingQuoteRequest {
    id: bigint;
    status: string;
    subject: string;
    name: string;
    submittedAt: bigint;
    language: string;
    quoteNotes: string;
    phone: string;
    finalPdfUrl: string;
    format: string;
    fileUrl: string;
}
export interface BusinessInfo {
    hours: string;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface Inquiry {
    name: string;
    message: string;
    phone: string;
}
export interface UserProfile {
    customerName?: string;
    deliveryAddress?: string;
    name: string;
    phone: string;
}
export interface UpiSettings {
    upiId: string;
    qrCodeUrl: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptDelivery(orderId: bigint): Promise<void>;
    addAttendanceRecord(mobile: string, date: string, status: string): Promise<void>;
    addCatalogItem(input: CatalogItemInput): Promise<bigint>;
    addExpense(category: string, amount: number, date: string, paymentMode: string, note: string, addedBy: string): Promise<bigint>;
    addKhataDue(phone: string, customerName: string, amount: number): Promise<number>;
    addManualIncome(category: string, amount: number, date: string, paymentMode: string, description: string): Promise<bigint>;
    addRider(name: string, mobile: string, pin: string): Promise<void>;
    addStaffLedgerEntry(mobile: string, date: string, description: string, amount: number, entryType: string): Promise<bigint>;
    addTeamMember(name: string, mobile: string, pin: string, role: string, baseSalary: number): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimAdminWithMasterKey(key: string): Promise<boolean>;
    clearKhataDue(phone: string, amountPaid: number): Promise<number>;
    deductWallet(phone: string, amount: number): Promise<number>;
    deductWalletForOrder(phone: string, amount: number): Promise<number>;
    deleteCatalogItem(id: bigint): Promise<void>;
    deleteExpense(id: bigint): Promise<void>;
    deleteManualIncome(id: bigint): Promise<void>;
    deleteReview(id: bigint): Promise<void>;
    exportBulkLeadsToCsv(): Promise<string>;
    filterOrders(filters: FilterOrders): Promise<Array<OrderRecord>>;
    generateOtp(phone: string): Promise<string>;
    getAllCatalogItems(): Promise<Array<CatalogItem>>;
    getAllKhataEntries(): Promise<Array<KhataEntry>>;
    getAllReviews(): Promise<Array<Review>>;
    getAllShopOrders(): Promise<Array<ShopOrder>>;
    getAllSupportTickets(): Promise<Array<SupportTicket>>;
    getAllTypesettingQuotes(): Promise<Array<TypesettingQuoteRequest>>;
    getAttendanceByDate(date: string): Promise<Array<AttendanceRecord>>;
    getAttendanceForMobile(mobile: string): Promise<Array<AttendanceRecord>>;
    getBusinessInfo(): Promise<BusinessInfo>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCatalogItem(id: bigint): Promise<CatalogItem | null>;
    getCustomerProfile(phone: string): Promise<{
        customerName: string;
        deliveryAddress: string;
    } | null>;
    getExpenses(): Promise<Array<ExpenseEntry>>;
    getInquiries(): Promise<Array<Inquiry>>;
    getKhataEntry(phone: string): Promise<KhataEntry | null>;
    getManualIncomes(): Promise<Array<ManualIncomeEntry>>;
    getOrderDeliveryOtp(orderId: bigint, phone: string): Promise<string>;
    getOrdersByPhone(phone: string): Promise<Array<OrderRecord>>;
    getPosSales(): Promise<Array<PosSale>>;
    getPosSalesByPhone(phone: string): Promise<Array<PosSale>>;
    getPublishedCatalogItems(): Promise<Array<CatalogItem>>;
    getPublishedReviews(): Promise<Array<Review>>;
    getReadyForDeliveryOrders(): Promise<Array<MaskedShopOrder>>;
    getRiders(): Promise<Array<Rider>>;
    getStaffLedgerEntries(mobile: string): Promise<Array<StaffLedgerEntry>>;
    getSupportTickets(customerMobile: string): Promise<Array<SupportTicket>>;
    getTeamMemberActive(mobile: string): Promise<boolean>;
    getUpiSettings(): Promise<UpiSettings | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWalletBalance(phone: string): Promise<number>;
    importBulkLeadsFromCsv(csv: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markOrderDelivered(orderId: bigint, otp: string): Promise<ShopOrder>;
    placeCscShopOrder(phone: string, customerName: string, deliveryMethod: string, deliveryAddress: string, paymentMethod: string, items: Array<ShopOrderItem>, totalAmount: number, cscDocuments: Array<ExternalBlob>, cscSpecialDetails: string): Promise<ShopOrder>;
    placeShopOrder(phone: string, customerName: string, deliveryMethod: string, deliveryAddress: string, paymentMethod: string, items: Array<ShopOrderItem>, totalAmount: number): Promise<ShopOrder>;
    rechargeWallet(phone: string, amount: number): Promise<number>;
    recordPosSale(items: Array<PosSaleItem>, totalAmount: number, paymentMethod: string, customerPhone: string, staffMobile: string): Promise<bigint>;
    removeRider(mobile: string): Promise<void>;
    resetStaffPin(mobile: string, newPin: string): Promise<void>;
    resolveSupportTicket(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCustomerProfile(phone: string, customerName: string, deliveryAddress: string): Promise<void>;
    seedReviews(): Promise<void>;
    setBusinessInfo(ownInfo: BusinessInfo): Promise<void>;
    setUpiSettings(upiId: string, qrCodeUrl: string): Promise<void>;
    submitInquiry(name: string, phone: string, message: string): Promise<void>;
    submitOrder(name: string, phone: string, serviceType: string, instructions: string, fileUrl: string): Promise<bigint>;
    submitOrderFull(input: ServiceOrder): Promise<bigint>;
    submitReview(orderId: bigint, customerName: string, customerPhone: string, location: string, serviceRating: bigint, serviceComment: string, deliveryRating: bigint | null, deliveryComment: string | null): Promise<bigint>;
    submitSupportTicket(orderId: string, customerMobile: string, complaint: string): Promise<bigint>;
    submitTypesettingQuoteRequest(input: TypesettingQuoteRequestInput): Promise<bigint>;
    togglePublishCatalogItem(id: bigint): Promise<void>;
    toggleReviewPublished(id: bigint): Promise<void>;
    toggleTeamMemberActive(mobile: string, isActive: boolean): Promise<void>;
    updateCatalogItem(id: bigint, input: CatalogItemInput): Promise<void>;
    updateExpense(id: bigint, category: string, amount: number, date: string, paymentMode: string, note: string): Promise<void>;
    updateLeadFinalPdf(id: bigint, finalPdfUrl: string): Promise<void>;
    updateLeadQuoteNotes(id: bigint, notes: string): Promise<void>;
    updateManualIncome(id: bigint, category: string, amount: number, date: string, paymentMode: string, description: string): Promise<void>;
    updateOrderStatus(id: bigint, status: string): Promise<void>;
    updateRiderSalary(mobile: string, baseSalary: number): Promise<void>;
    updateShopOrderStatus(id: bigint, status: string): Promise<void>;
    updateTypesettingQuoteStatus(id: bigint, update: TypesettingQuoteUpdate): Promise<void>;
    uploadCscFinalOutput(orderId: bigint, file: ExternalBlob): Promise<void>;
    verifyBulkStaff(mobile: string, pin: string): Promise<boolean>;
    verifyOtp(phone: string, code: string): Promise<boolean>;
    verifyRider(mobile: string, pin: string): Promise<boolean>;
    verifyStaff(mobile: string, pin: string): Promise<boolean>;
}
import type { CatalogItem as _CatalogItem, CatalogItemInput as _CatalogItemInput, ExternalBlob as _ExternalBlob, FilterOrders as _FilterOrders, KhataEntry as _KhataEntry, OrderRecord as _OrderRecord, Review as _Review, ServiceOrder as _ServiceOrder, ShopOrder as _ShopOrder, ShopOrderItem as _ShopOrderItem, UpiSettings as _UpiSettings, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptDelivery(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptDelivery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptDelivery(arg0);
            return result;
        }
    }
    async addAttendanceRecord(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAttendanceRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAttendanceRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async addCatalogItem(arg0: CatalogItemInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCatalogItem(await to_candid_CatalogItemInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCatalogItem(await to_candid_CatalogItemInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addExpense(arg0: string, arg1: number, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addKhataDue(arg0: string, arg1: string, arg2: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.addKhataDue(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKhataDue(arg0, arg1, arg2);
            return result;
        }
    }
    async addManualIncome(arg0: string, arg1: number, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addManualIncome(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addManualIncome(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addRider(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRider(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRider(arg0, arg1, arg2);
            return result;
        }
    }
    async addStaffLedgerEntry(arg0: string, arg1: string, arg2: string, arg3: number, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaffLedgerEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaffLedgerEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addTeamMember(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeamMember(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeamMember(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimAdminWithMasterKey(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdminWithMasterKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdminWithMasterKey(arg0);
            return result;
        }
    }
    async clearKhataDue(arg0: string, arg1: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.clearKhataDue(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearKhataDue(arg0, arg1);
            return result;
        }
    }
    async deductWallet(arg0: string, arg1: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.deductWallet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductWallet(arg0, arg1);
            return result;
        }
    }
    async deductWalletForOrder(arg0: string, arg1: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.deductWalletForOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductWalletForOrder(arg0, arg1);
            return result;
        }
    }
    async deleteCatalogItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCatalogItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCatalogItem(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteManualIncome(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteManualIncome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteManualIncome(arg0);
            return result;
        }
    }
    async deleteReview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async exportBulkLeadsToCsv(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportBulkLeadsToCsv();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportBulkLeadsToCsv();
            return result;
        }
    }
    async filterOrders(arg0: FilterOrders): Promise<Array<OrderRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterOrders(to_candid_FilterOrders_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterOrders(to_candid_FilterOrders_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateOtp(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOtp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOtp(arg0);
            return result;
        }
    }
    async getAllCatalogItems(): Promise<Array<CatalogItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCatalogItems();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCatalogItems();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllKhataEntries(): Promise<Array<KhataEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKhataEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKhataEntries();
            return result;
        }
    }
    async getAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviews();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviews();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllShopOrders(): Promise<Array<ShopOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShopOrders();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShopOrders();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSupportTickets(): Promise<Array<SupportTicket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSupportTickets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSupportTickets();
            return result;
        }
    }
    async getAllTypesettingQuotes(): Promise<Array<TypesettingQuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTypesettingQuotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTypesettingQuotes();
            return result;
        }
    }
    async getAttendanceByDate(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByDate(arg0);
            return result;
        }
    }
    async getAttendanceForMobile(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceForMobile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceForMobile(arg0);
            return result;
        }
    }
    async getBusinessInfo(): Promise<BusinessInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessInfo();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCatalogItem(arg0: bigint): Promise<CatalogItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCatalogItem(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCatalogItem(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerProfile(arg0: string): Promise<{
        customerName: string;
        deliveryAddress: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenses(): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return result;
        }
    }
    async getInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiries();
            return result;
        }
    }
    async getKhataEntry(arg0: string): Promise<KhataEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKhataEntry(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKhataEntry(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getManualIncomes(): Promise<Array<ManualIncomeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getManualIncomes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManualIncomes();
            return result;
        }
    }
    async getOrderDeliveryOtp(arg0: bigint, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderDeliveryOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderDeliveryOtp(arg0, arg1);
            return result;
        }
    }
    async getOrdersByPhone(arg0: string): Promise<Array<OrderRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByPhone(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByPhone(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPosSales(): Promise<Array<PosSale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosSales();
            return result;
        }
    }
    async getPosSalesByPhone(arg0: string): Promise<Array<PosSale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosSalesByPhone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosSalesByPhone(arg0);
            return result;
        }
    }
    async getPublishedCatalogItems(): Promise<Array<CatalogItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedCatalogItems();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedCatalogItems();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedReviews();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedReviews();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReadyForDeliveryOrders(): Promise<Array<MaskedShopOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReadyForDeliveryOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReadyForDeliveryOrders();
            return result;
        }
    }
    async getRiders(): Promise<Array<Rider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiders();
            return result;
        }
    }
    async getStaffLedgerEntries(arg0: string): Promise<Array<StaffLedgerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffLedgerEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffLedgerEntries(arg0);
            return result;
        }
    }
    async getSupportTickets(arg0: string): Promise<Array<SupportTicket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportTickets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportTickets(arg0);
            return result;
        }
    }
    async getTeamMemberActive(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMemberActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMemberActive(arg0);
            return result;
        }
    }
    async getUpiSettings(): Promise<UpiSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpiSettings();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpiSettings();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletBalance(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance(arg0);
            return result;
        }
    }
    async importBulkLeadsFromCsv(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importBulkLeadsFromCsv(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importBulkLeadsFromCsv(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markOrderDelivered(arg0: bigint, arg1: string): Promise<ShopOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.markOrderDelivered(arg0, arg1);
                return from_candid_ShopOrder_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markOrderDelivered(arg0, arg1);
            return from_candid_ShopOrder_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeCscShopOrder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<ShopOrderItem>, arg6: number, arg7: Array<ExternalBlob>, arg8: string): Promise<ShopOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.placeCscShopOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg7), arg8);
                return from_candid_ShopOrder_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeCscShopOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg7), arg8);
            return from_candid_ShopOrder_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeShopOrder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<ShopOrderItem>, arg6: number): Promise<ShopOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.placeShopOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_ShopOrder_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeShopOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_ShopOrder_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async rechargeWallet(arg0: string, arg1: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.rechargeWallet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rechargeWallet(arg0, arg1);
            return result;
        }
    }
    async recordPosSale(arg0: Array<PosSaleItem>, arg1: number, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPosSale(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPosSale(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async removeRider(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRider(arg0);
            return result;
        }
    }
    async resetStaffPin(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetStaffPin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetStaffPin(arg0, arg1);
            return result;
        }
    }
    async resolveSupportTicket(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveSupportTicket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveSupportTicket(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCustomerProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCustomerProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCustomerProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async seedReviews(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedReviews();
            return result;
        }
    }
    async setBusinessInfo(arg0: BusinessInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBusinessInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBusinessInfo(arg0);
            return result;
        }
    }
    async setUpiSettings(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUpiSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUpiSettings(arg0, arg1);
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2);
            return result;
        }
    }
    async submitOrder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrder(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrder(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitOrderFull(arg0: ServiceOrder): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrderFull(await to_candid_ServiceOrder_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrderFull(await to_candid_ServiceOrder_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitReview(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: bigint | null, arg7: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n45(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n45(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async submitSupportTicket(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSupportTicket(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSupportTicket(arg0, arg1, arg2);
            return result;
        }
    }
    async submitTypesettingQuoteRequest(arg0: TypesettingQuoteRequestInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTypesettingQuoteRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTypesettingQuoteRequest(arg0);
            return result;
        }
    }
    async togglePublishCatalogItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePublishCatalogItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePublishCatalogItem(arg0);
            return result;
        }
    }
    async toggleReviewPublished(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleReviewPublished(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleReviewPublished(arg0);
            return result;
        }
    }
    async toggleTeamMemberActive(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTeamMemberActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTeamMemberActive(arg0, arg1);
            return result;
        }
    }
    async updateCatalogItem(arg0: bigint, arg1: CatalogItemInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCatalogItem(arg0, await to_candid_CatalogItemInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCatalogItem(arg0, await to_candid_CatalogItemInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateExpense(arg0: bigint, arg1: string, arg2: number, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateLeadFinalPdf(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadFinalPdf(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadFinalPdf(arg0, arg1);
            return result;
        }
    }
    async updateLeadQuoteNotes(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadQuoteNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadQuoteNotes(arg0, arg1);
            return result;
        }
    }
    async updateManualIncome(arg0: bigint, arg1: string, arg2: number, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateManualIncome(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateManualIncome(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1);
            return result;
        }
    }
    async updateRiderSalary(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRiderSalary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRiderSalary(arg0, arg1);
            return result;
        }
    }
    async updateShopOrderStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShopOrderStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShopOrderStatus(arg0, arg1);
            return result;
        }
    }
    async updateTypesettingQuoteStatus(arg0: bigint, arg1: TypesettingQuoteUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTypesettingQuoteStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTypesettingQuoteStatus(arg0, arg1);
            return result;
        }
    }
    async uploadCscFinalOutput(arg0: bigint, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadCscFinalOutput(arg0, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadCscFinalOutput(arg0, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyBulkStaff(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyBulkStaff(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyBulkStaff(arg0, arg1);
            return result;
        }
    }
    async verifyOtp(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0, arg1);
            return result;
        }
    }
    async verifyRider(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyRider(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyRider(arg0, arg1);
            return result;
        }
    }
    async verifyStaff(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyStaff(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyStaff(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_CatalogItem_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CatalogItem): Promise<CatalogItem> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_OrderRecord_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderRecord): Promise<OrderRecord> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_ShopOrder_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShopOrder): Promise<ShopOrder> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CatalogItem]): Promise<CatalogItem | null> {
    return value.length === 0 ? null : await from_candid_CatalogItem_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        customerName: string;
        deliveryAddress: string;
    }]): {
    customerName: string;
    deliveryAddress: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KhataEntry]): KhataEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UpiSettings]): UpiSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    serviceType: string;
    name: string;
    submittedAt: bigint;
    instructions: string;
    uploadedFiles: Array<_ExternalBlob>;
    phone: string;
    fileUrl: string;
}): Promise<{
    id: bigint;
    status: string;
    serviceType: string;
    name: string;
    submittedAt: bigint;
    instructions: string;
    uploadedFiles: Array<ExternalBlob>;
    phone: string;
    fileUrl: string;
}> {
    return {
        id: value.id,
        status: value.status,
        serviceType: value.serviceType,
        name: value.name,
        submittedAt: value.submittedAt,
        instructions: value.instructions,
        uploadedFiles: await from_candid_vec_n19(_uploadFile, _downloadFile, value.uploadedFiles),
        phone: value.phone,
        fileUrl: value.fileUrl
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    requiredDocuments: string;
    stockStatus: string;
    requiresPdfCalc: boolean;
    published: boolean;
    name: string;
    createdAt: bigint;
    description: string;
    category: string;
    price: string;
    mediaFiles: Array<_ExternalBlob>;
    mediaTypes: Array<string>;
}): Promise<{
    id: bigint;
    requiredDocuments: string;
    stockStatus: string;
    requiresPdfCalc: boolean;
    published: boolean;
    name: string;
    createdAt: bigint;
    description: string;
    category: string;
    price: string;
    mediaFiles: Array<ExternalBlob>;
    mediaTypes: Array<string>;
}> {
    return {
        id: value.id,
        requiredDocuments: value.requiredDocuments,
        stockStatus: value.stockStatus,
        requiresPdfCalc: value.requiresPdfCalc,
        published: value.published,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        category: value.category,
        price: value.price,
        mediaFiles: await from_candid_vec_n19(_uploadFile, _downloadFile, value.mediaFiles),
        mediaTypes: value.mediaTypes
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    deliveryRating: [] | [bigint];
    customerPhone: string;
    serviceRating: bigint;
    published: boolean;
    createdAt: bigint;
    orderId: bigint;
    location: string;
    deliveryComment: [] | [string];
    serviceComment: string;
}): {
    id: bigint;
    customerName: string;
    deliveryRating?: bigint;
    customerPhone: string;
    serviceRating: bigint;
    published: boolean;
    createdAt: bigint;
    orderId: bigint;
    location: string;
    deliveryComment?: string;
    serviceComment: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        deliveryRating: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.deliveryRating)),
        customerPhone: value.customerPhone,
        serviceRating: value.serviceRating,
        published: value.published,
        createdAt: value.createdAt,
        orderId: value.orderId,
        location: value.location,
        deliveryComment: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.deliveryComment)),
        serviceComment: value.serviceComment
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: string;
    deliveryAddress: string;
    paymentMethod: string;
    deliveryOtp: string;
    cscFinalOutput: [] | [_ExternalBlob];
    createdAt: bigint;
    deliveryMethod: string;
    cscDocuments: Array<_ExternalBlob>;
    cscSpecialDetails: string;
    totalAmount: number;
    phone: string;
    items: Array<_ShopOrderItem>;
}): Promise<{
    id: bigint;
    customerName: string;
    status: string;
    deliveryAddress: string;
    paymentMethod: string;
    deliveryOtp: string;
    cscFinalOutput?: ExternalBlob;
    createdAt: bigint;
    deliveryMethod: string;
    cscDocuments: Array<ExternalBlob>;
    cscSpecialDetails: string;
    totalAmount: number;
    phone: string;
    items: Array<ShopOrderItem>;
}> {
    return {
        id: value.id,
        customerName: value.customerName,
        status: value.status,
        deliveryAddress: value.deliveryAddress,
        paymentMethod: value.paymentMethod,
        deliveryOtp: value.deliveryOtp,
        cscFinalOutput: record_opt_to_undefined(await from_candid_opt_n31(_uploadFile, _downloadFile, value.cscFinalOutput)),
        createdAt: value.createdAt,
        deliveryMethod: value.deliveryMethod,
        cscDocuments: await from_candid_vec_n19(_uploadFile, _downloadFile, value.cscDocuments),
        cscSpecialDetails: value.cscSpecialDetails,
        totalAmount: value.totalAmount,
        phone: value.phone,
        items: value.items
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: [] | [string];
    deliveryAddress: [] | [string];
    name: string;
    phone: string;
}): {
    customerName?: string;
    deliveryAddress?: string;
    name: string;
    phone: string;
} {
    return {
        customerName: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.customerName)),
        deliveryAddress: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.deliveryAddress)),
        name: value.name,
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderRecord>): Promise<Array<OrderRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_OrderRecord_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CatalogItem>): Promise<Array<CatalogItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CatalogItem_n22(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n25(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShopOrder>): Promise<Array<ShopOrder>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ShopOrder_n29(_uploadFile, _downloadFile, x)));
}
async function to_candid_CatalogItemInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CatalogItemInput): Promise<_CatalogItemInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FilterOrders_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FilterOrders): _FilterOrders {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ServiceOrder_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceOrder): Promise<_ServiceOrder> {
    return await to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: string;
    serviceType?: string;
    name?: string;
    phone?: string;
}): {
    status: [] | [string];
    serviceType: [] | [string];
    name: [] | [string];
    phone: [] | [string];
} {
    return {
        status: value.status ? candid_some(value.status) : candid_none(),
        serviceType: value.serviceType ? candid_some(value.serviceType) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName?: string;
    deliveryAddress?: string;
    name: string;
    phone: string;
}): {
    customerName: [] | [string];
    deliveryAddress: [] | [string];
    name: string;
    phone: string;
} {
    return {
        customerName: value.customerName ? candid_some(value.customerName) : candid_none(),
        deliveryAddress: value.deliveryAddress ? candid_some(value.deliveryAddress) : candid_none(),
        name: value.name,
        phone: value.phone
    };
}
async function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    files: Array<ExternalBlob>;
    serviceType: string;
    name: string;
    instructions: string;
    phone: string;
}): Promise<{
    files: Array<_ExternalBlob>;
    serviceType: string;
    name: string;
    instructions: string;
    phone: string;
}> {
    return {
        files: await to_candid_vec_n10(_uploadFile, _downloadFile, value.files),
        serviceType: value.serviceType,
        name: value.name,
        instructions: value.instructions,
        phone: value.phone
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requiredDocuments: string;
    stockStatus: string;
    requiresPdfCalc: boolean;
    name: string;
    description: string;
    category: string;
    price: string;
    mediaFiles: Array<ExternalBlob>;
    mediaTypes: Array<string>;
}): Promise<{
    requiredDocuments: string;
    stockStatus: string;
    requiresPdfCalc: boolean;
    name: string;
    description: string;
    category: string;
    price: string;
    mediaFiles: Array<_ExternalBlob>;
    mediaTypes: Array<string>;
}> {
    return {
        requiredDocuments: value.requiredDocuments,
        stockStatus: value.stockStatus,
        requiresPdfCalc: value.requiresPdfCalc,
        name: value.name,
        description: value.description,
        category: value.category,
        price: value.price,
        mediaFiles: await to_candid_vec_n10(_uploadFile, _downloadFile, value.mediaFiles),
        mediaTypes: value.mediaTypes
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
